logger:
  level: INFO

global:
  random.seed: 1
  gpu.id: 1

training:
  log.results: "../data/training.log"

  optimize.parameters: False  # If this is set to True, the optimizer overrides the values for the model parameters
  optimize.num.trails: 3
  optimize.save.history: ../trails.today.json

  negative.samples.per.entity: -1
  null.per.dataset: -1

evaluation:

dataset:
  type: NEELDataset
  path_to_dataset: ""
  precomputed_candidates: ""
  subsample: 0.01

entity.linking:  # These parameters are used to instantiate an entity linker
  candidates.to.retrieve: 25
  max.match.diff: 2

  linker: HeuristicsLinker
  linker.options:
    max_mention_len: 4
    num_candidates: 10
    prefer_longer_matches: True
    no_mentions_overlap: True
    caseless_mode: False
    mention_context_size: 2

model:  # If an entity linker features a trained model, these parameters are used to instantiate it
  models.save.path: "../trainedmodels/"
  word.embeddings: "../../resources/glove/glove.6B.50d.txt"
  epochs: 200
  model.checkpoint: True

  negative.class.weight: [0.05, 0.25]

  monitor: "acc"
  early.stopping: 10

  sem.layer.size: 25
  poss.emb.size: 3
  activation: relu
  dropout: 0.2

wikidata:
  backend: "http://knowledgebase:8890/sparql"
  timeout: 20
  filter.out.relation.classes: "rq"
  
